[book]
title = "Infrastructure"
authors = ["kaj"]
language = "en"

[output.html]
edit-url-template = "https://github.com/knekvasil/library/edit/master/infra/src/{path}"
git-repository-url = "https://github.com/knekvasil/library"
